server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/ # "optional:" Se não encontrar ele não vai falhar 
  cloud:
    config:
      profile: prod

# Expõe todos os endpoints do Spring Boot Actuator
# O Actuator mostra informações sobre a saúde de uma aplicação, logs, dentre outras funcionalidades
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

# Se o configserver nao funcionar, então será usado esse config default 
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"

