spring:
  application:
    name: greeting-service

# Expõe todos os endpoints do Spring Boot Actuator
# O Actuator mostra informações sobre a saúde de uma aplicação, logs, dentre outras funcionalidades
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  
greeting-service:
  greeting: "Wello"
  default-value: "Word"

